#!/usr/bin/env bash
pushd ./bat-extras >/dev/null

function check_installed() {
    local prefix="$1"
    local scripts=(./src/*)
    # check if all the scripts are already installed
    for script in "${scripts[@]}"; do
        local name=$(basename "${script%.*}")
        if ! [[ -f "$prefix/$name" ]]; then
            return -1
        fi
    done
    return 0
}

prefix="${HOME}/.local/bin"
echo -en " bat-extras"

if ! check_installed "$prefix"; then
    # echo ""
    log echo "$(small)  this may take several moments...$(reset)"
    log ./build.sh --install --prefix=${prefix}
fi

echo "$(small)  ...done$(reset)"
unset prefix

popd >/dev/null