#!/usr/bin/env bash

function insert-into() {
    local file="$1"
    local line=1
    local text="$2"

    # Insert the text at the specified line number
    if grep -q "$text" "$file"; then
        echo "Text already exists in $file"
        return
    fi
    # sed -i "${line}s|^|${text}\n|" "$file"
    echo "$text" >> "$file"
}

function include-scripts() {
    insert-into "${HOME}/.bashrc" "# >>> Install Custom dotfiles >>>"

    for inc in ./include/*; do
        f=$(realpath "$inc")
        insert-into "${HOME}/.bashrc" "source $f"
    done

    insert-into "${HOME}/.bashrc" "# <<< Install Custom dotfiles <<<"
}

log include-scripts
