#!/usr/bin/env bash

function insert-into() {
    local file="$1"
    local line=1
    local text="$2"

    # Insert the text at the specified line number
    if grep -q "$text" "$file"; then
        echo "Text already exists in $file"
        return
    fi
    sed -i "${line}s|^|${text}\n|" "$file"
}

function include-scripts() {
    insert-into ./dot-bash_profile "# >>> Install Custom dotfiles >>>"

    for inc in ./include/*; do
        f=$(realpath "$inc")
        insert-into ./dot-bash_profile "source $f"
    done

    insert-into ./dot-bash_profile "# <<< Install Custom dotfiles <<<"
}

log include-scripts
